backend:
  name: git-gateway
  branch: dependabot/bundler/addressable-2.8.1 # La tua branch principale, solitamente 'main' o 'master'

media_folder: "assets" # Dove saranno caricate le immagini
public_folder: "/assets" # Path pubblico per le immagini

collections:
  - name: "books"
    label: "Books"
    folder: "_book"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "ISBN", name: "isbn", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Data", name: "datapub", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Dewey Number", name: "dewey", widget: "string" }
      - { label: "Cover Image", name: "copertina", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "libri" }
  - name: "page"
    label: "page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    format: "yaml-frontmatter"
    extension: "md"
    preview_path: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Permalink", name: "Permalink", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
